name: Build & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: ${{ matrix.platform.runner }} / Xcode ${{ matrix.platform.xcode }} / ${{ matrix.config }}
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        config: ['debug', 'release']
        platform:
          - xcode: '16.4'
            runner: macos-15
            ios_simulator_name: iPhone 16 Pro
            ios_simulator_os: '18.6'
            watchos_simulator_name: Apple Watch Series 10 (42mm)
            watchos_simulator_os: '11.5'
          - xcode: '26.0.1'
            runner: macos-26
            ios_simulator_name: iPhone 17 Pro
            ios_simulator_os: '26.0.1'
            watchos_simulator_name: Apple Watch Series 11 (46mm)
            watchos_simulator_os: '26.0'
    env:
      IOS_SIMULATOR_NAME: ${{ matrix.platform.ios_simulator_name }}
      IOS_SIMULATOR_OS: ${{ matrix.platform.ios_simulator_os }}
      WATCHOS_SIMULATOR_NAME: ${{ matrix.platform.watchos_simulator_name }}
      WATCHOS_SIMULATOR_OS: ${{ matrix.platform.watchos_simulator_os }}
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode ${{ matrix.platform.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.platform.xcode }}.app
      - name: Skip macro validation
        run: defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES
      - name: Run library tests
        run: make test
      - name: Run example app tests
        run: make test-exampleApp
      - name: Build platforms ${{ matrix.config }}
        run: CONFIG=${{ matrix.config }} make build-all-platforms
      - name: Build for library evolution
        run: make build-for-library-evolution
