name: Build & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  macos-15:
    name: macOS 15
    runs-on: macos-15
    strategy:
      matrix:
        config: ['debug', 'release']
        xcode: ['16.2']
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Skip macro validation
        run: defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES
      - name: Run library tests
        run: make test
      - name: Run example app tests
        run: make test-exampleApp
      - name: Build platforms ${{ matrix.config }}
        run: CONFIG=${{ matrix.config }} make build-all-platforms
      - name: Build for library evolution
        run: make build-for-library-evolution